
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Mirror server.js env resolution: .env.local takes precedence over .env,
// so Prisma Studio always targets the same database the server connects to.
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config();
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("LOCAL_DATABASE_URL"),
  },
});
