--
-- Schema snapshot generated by building/dump_schema.js on 2026-08-04T19:54:05.073Z
-- Source: Tik_Surfer_multi_fix
--

--
-- PostgreSQL database dump
--

\restrict OhscuvA8vhpifGFtuzUQ9YHVuLfW0xp43ZUSNajfAMgbDnOddDG9xdsZ4FIY5EF

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_table_access_method = heap;

--
-- Name: comment_scrape_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_scrape_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    post_shortcode character varying(255),
    api_calls integer DEFAULT 0,
    comments_scraped integer DEFAULT 0,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id character varying(255) NOT NULL,
    post_shortcode character varying(255) NOT NULL,
    username character varying(255),
    user_id character varying(255),
    text text,
    likes_count integer DEFAULT 0,
    reply_count integer DEFAULT 0,
    profile_pic_url text,
    commented_at timestamp with time zone,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ig_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ig_users (
    id character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    follower_count bigint DEFAULT 0,
    following_count bigint DEFAULT 0,
    media_count integer DEFAULT 0,
    biography text,
    external_url text,
    business_category character varying(255),
    is_verified boolean DEFAULT false,
    role character varying(50) DEFAULT 'reference'::character varying,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    display_name character varying(255),
    video_count integer DEFAULT 0,
    signature text,
    bio_link text,
    region character varying(100),
    avatar_url text
);


--
-- Name: keyword_search_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.keyword_search_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    keyword_id uuid NOT NULL,
    project_id uuid NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying NOT NULL,
    videos_captured integer DEFAULT 0,
    scroll_position integer DEFAULT 0,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT keyword_search_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])))
);


--
-- Name: post_metrics_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_metrics_history (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    post_shortcode character varying(255),
    likes_count integer DEFAULT 0,
    comments_count integer DEFAULT 0,
    video_view_count integer DEFAULT 0,
    view_count bigint DEFAULT 0,
    repost_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    bookmark_count integer DEFAULT 0,
    captured_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: post_relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_relations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    post_shortcode character varying(255),
    username character varying(255),
    relation_type character varying(50) NOT NULL
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    shortcode character varying(255) NOT NULL,
    owner_username character varying(255),
    post_url text,
    caption text,
    image_url text,
    video_url text,
    is_video boolean DEFAULT false,
    is_carousel boolean DEFAULT false,
    is_paid boolean DEFAULT false,
    classification character varying(100) DEFAULT 'Normal Post'::character varying,
    type character varying(50) DEFAULT 'normal'::character varying,
    collective_reach bigint DEFAULT 0,
    reach_breakdown jsonb DEFAULT '[]'::jsonb,
    scraped_from_profile character varying(255),
    is_reference boolean DEFAULT false,
    view_count bigint DEFAULT 0,
    repost_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    bookmark_count integer DEFAULT 0,
    posted_at timestamp with time zone,
    first_captured_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    hashtags jsonb DEFAULT '[]'::jsonb,
    mentions jsonb DEFAULT '[]'::jsonb,
    music_title character varying(500),
    music_author character varying(255),
    duet_from character varying(255),
    stitch_from character varying(255),
    is_hidden boolean DEFAULT false,
    hidden_at timestamp with time zone,
    deleted_at timestamp with time zone
);


--
-- Name: project_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_posts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    post_shortcode character varying(255) NOT NULL,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: project_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    username character varying(255) NOT NULL,
    role character varying(50) DEFAULT 'tracked'::character varying,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    pinned boolean DEFAULT false
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: scrape_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scrape_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid NOT NULL,
    post_shortcode character varying(255) NOT NULL,
    page_number integer DEFAULT 1,
    status character varying(50) DEFAULT 'pending'::character varying,
    end_cursor text DEFAULT ''::text,
    comments_scraped integer DEFAULT 0,
    retry_count integer DEFAULT 0,
    max_retries integer DEFAULT 3,
    error_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp with time zone,
    completed_at timestamp with time zone
);


--
-- Name: scrape_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scrape_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    profile_username character varying(255),
    status character varying(50) DEFAULT 'pending'::character varying,
    total_posts integer DEFAULT 0,
    total_jobs integer DEFAULT 0,
    completed_jobs integer DEFAULT 0,
    total_comments_scraped integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    project_id uuid
);


--
-- Name: search_keywords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_keywords (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    keyword character varying(255) NOT NULL,
    platform character varying(50) DEFAULT 'tiktok'::character varying NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying NOT NULL,
    total_videos integer DEFAULT 0,
    total_creators integer DEFAULT 0,
    total_views bigint DEFAULT 0,
    total_engagement bigint DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    source_type character varying(20) DEFAULT 'search'::character varying NOT NULL,
    tiktok_challenge_id character varying(50),
    CONSTRAINT search_keywords_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['search'::character varying, 'hashtag'::character varying])::text[]))),
    CONSTRAINT search_keywords_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'paused'::character varying, 'archived'::character varying])::text[])))
);


--
-- Name: tiktok_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_comments (
    id character varying(255) NOT NULL,
    video_id character varying(255) NOT NULL,
    keyword_id uuid,
    commenter_username character varying(255),
    commenter_user_id character varying(255),
    commenter_avatar_url text,
    text text,
    likes_count integer DEFAULT 0,
    reply_count integer DEFAULT 0,
    is_reply boolean DEFAULT false,
    parent_comment_id character varying(255),
    commented_at timestamp with time zone,
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tiktok_creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_creators (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tiktok_user_id character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    display_name character varying(255),
    avatar_url text,
    follower_count bigint DEFAULT 0,
    following_count integer DEFAULT 0,
    video_count integer DEFAULT 0,
    biography text,
    is_verified boolean DEFAULT false,
    first_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tiktok_graphql_captures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_graphql_captures (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid,
    keyword_id uuid,
    video_id character varying(255),
    creator_id uuid,
    url text NOT NULL,
    method character varying(10) DEFAULT 'GET'::character varying,
    capture_type character varying(50) DEFAULT 'unknown'::character varying,
    request_body jsonb,
    response_body jsonb,
    captured_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tiktok_hashtags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_hashtags (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    video_id character varying(255) NOT NULL,
    keyword_id uuid,
    tag character varying(255) NOT NULL,
    view_count bigint DEFAULT 0
);


--
-- Name: tiktok_keyword_creators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_keyword_creators (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    keyword_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    video_count integer DEFAULT 1,
    total_views bigint DEFAULT 0,
    first_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: tiktok_users; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.tiktok_users AS
 SELECT id,
    username,
    follower_count,
    following_count,
    media_count,
    biography,
    external_url,
    business_category,
    is_verified,
    role,
    scraped_at,
    display_name,
    video_count,
    signature,
    bio_link,
    region,
    avatar_url
   FROM public.ig_users;


--
-- Name: tiktok_videos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiktok_videos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    video_id character varying(255) NOT NULL,
    keyword_id uuid NOT NULL,
    session_id uuid,
    creator_id uuid,
    project_id uuid NOT NULL,
    caption text,
    video_url text,
    thumbnail_url text,
    duration integer DEFAULT 0,
    views_count bigint DEFAULT 0,
    likes_count bigint DEFAULT 0,
    comments_count integer DEFAULT 0,
    shares_count integer DEFAULT 0,
    bookmarks_count integer DEFAULT 0,
    included_in_reach boolean DEFAULT true,
    included_in_engagement boolean DEFAULT true,
    included_in_reporting boolean DEFAULT true,
    manual_reviewed boolean DEFAULT false,
    relevance_score integer DEFAULT 0,
    capture_status character varying(50) DEFAULT 'captured'::character varying NOT NULL,
    posted_at timestamp with time zone,
    captured_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_hidden boolean DEFAULT false,
    reposts_count integer DEFAULT 0,
    CONSTRAINT tiktok_videos_capture_status_check CHECK (((capture_status)::text = ANY ((ARRAY['captured'::character varying, 'comments_pending'::character varying, 'comments_partial'::character varying, 'comments_done'::character varying, 'failed'::character varying])::text[]))),
    CONSTRAINT tiktok_videos_relevance_score_check CHECK (((relevance_score >= 0) AND (relevance_score <= 100)))
);


--
-- Name: user_scraped_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_scraped_posts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    post_shortcode character varying(255),
    scraped_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying,
    plan character varying(50) DEFAULT 'none'::character varying,
    active_sessions integer DEFAULT 0,
    last_login timestamp with time zone,
    max_devices integer DEFAULT 3,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: comment_scrape_logs comment_scrape_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_scrape_logs
    ADD CONSTRAINT comment_scrape_logs_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: ig_users ig_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ig_users
    ADD CONSTRAINT ig_users_pkey PRIMARY KEY (id);


--
-- Name: ig_users ig_users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ig_users
    ADD CONSTRAINT ig_users_username_key UNIQUE (username);


--
-- Name: keyword_search_sessions keyword_search_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.keyword_search_sessions
    ADD CONSTRAINT keyword_search_sessions_pkey PRIMARY KEY (id);


--
-- Name: post_metrics_history post_metrics_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_metrics_history
    ADD CONSTRAINT post_metrics_history_pkey PRIMARY KEY (id);


--
-- Name: post_relations post_relations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_relations
    ADD CONSTRAINT post_relations_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (shortcode);


--
-- Name: project_posts project_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_posts
    ADD CONSTRAINT project_posts_pkey PRIMARY KEY (id);


--
-- Name: project_posts project_posts_project_id_post_shortcode_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_posts
    ADD CONSTRAINT project_posts_project_id_post_shortcode_key UNIQUE (project_id, post_shortcode);


--
-- Name: project_profiles project_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_profiles
    ADD CONSTRAINT project_profiles_pkey PRIMARY KEY (id);


--
-- Name: project_profiles project_profiles_project_id_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_profiles
    ADD CONSTRAINT project_profiles_project_id_username_key UNIQUE (project_id, username);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: scrape_jobs scrape_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_jobs
    ADD CONSTRAINT scrape_jobs_pkey PRIMARY KEY (id);


--
-- Name: scrape_sessions scrape_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_sessions
    ADD CONSTRAINT scrape_sessions_pkey PRIMARY KEY (id);


--
-- Name: search_keywords search_keywords_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_keywords
    ADD CONSTRAINT search_keywords_pkey PRIMARY KEY (id);


--
-- Name: search_keywords search_keywords_project_keyword_source_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_keywords
    ADD CONSTRAINT search_keywords_project_keyword_source_unique UNIQUE (project_id, keyword, source_type);


--
-- Name: tiktok_comments tiktok_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_comments
    ADD CONSTRAINT tiktok_comments_pkey PRIMARY KEY (id);


--
-- Name: tiktok_creators tiktok_creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_creators
    ADD CONSTRAINT tiktok_creators_pkey PRIMARY KEY (id);


--
-- Name: tiktok_creators tiktok_creators_tiktok_user_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_creators
    ADD CONSTRAINT tiktok_creators_tiktok_user_id_unique UNIQUE (tiktok_user_id);


--
-- Name: tiktok_creators tiktok_creators_username_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_creators
    ADD CONSTRAINT tiktok_creators_username_unique UNIQUE (username);


--
-- Name: tiktok_graphql_captures tiktok_graphql_captures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_graphql_captures
    ADD CONSTRAINT tiktok_graphql_captures_pkey PRIMARY KEY (id);


--
-- Name: tiktok_hashtags tiktok_hashtags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_hashtags
    ADD CONSTRAINT tiktok_hashtags_pkey PRIMARY KEY (id);


--
-- Name: tiktok_hashtags tiktok_hashtags_video_tag_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_hashtags
    ADD CONSTRAINT tiktok_hashtags_video_tag_unique UNIQUE (video_id, tag);


--
-- Name: tiktok_keyword_creators tiktok_keyword_creators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_keyword_creators
    ADD CONSTRAINT tiktok_keyword_creators_pkey PRIMARY KEY (id);


--
-- Name: tiktok_keyword_creators tiktok_keyword_creators_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_keyword_creators
    ADD CONSTRAINT tiktok_keyword_creators_unique UNIQUE (keyword_id, creator_id);


--
-- Name: tiktok_videos tiktok_videos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_pkey PRIMARY KEY (id);


--
-- Name: tiktok_videos tiktok_videos_video_keyword_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_video_keyword_unique UNIQUE (video_id, keyword_id);


--
-- Name: user_scraped_posts user_scraped_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_scraped_posts
    ADD CONSTRAINT user_scraped_posts_pkey PRIMARY KEY (id);


--
-- Name: user_scraped_posts user_scraped_posts_user_id_post_shortcode_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_scraped_posts
    ADD CONSTRAINT user_scraped_posts_user_id_post_shortcode_key UNIQUE (user_id, post_shortcode);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_comment_scrape_logs_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comment_scrape_logs_post ON public.comment_scrape_logs USING btree (post_shortcode);


--
-- Name: idx_comments_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_post ON public.comments USING btree (post_shortcode);


--
-- Name: idx_comments_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_username ON public.comments USING btree (username);


--
-- Name: idx_graphql_captures_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_graphql_captures_keyword ON public.tiktok_graphql_captures USING btree (keyword_id);


--
-- Name: idx_graphql_captures_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_graphql_captures_session ON public.tiktok_graphql_captures USING btree (session_id);


--
-- Name: idx_graphql_captures_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_graphql_captures_type ON public.tiktok_graphql_captures USING btree (capture_type);


--
-- Name: idx_graphql_captures_video; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_graphql_captures_video ON public.tiktok_graphql_captures USING btree (video_id);


--
-- Name: idx_kw_creators_creator; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kw_creators_creator ON public.tiktok_keyword_creators USING btree (creator_id);


--
-- Name: idx_kw_creators_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kw_creators_keyword ON public.tiktok_keyword_creators USING btree (keyword_id);


--
-- Name: idx_kw_sessions_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kw_sessions_keyword ON public.keyword_search_sessions USING btree (keyword_id);


--
-- Name: idx_kw_sessions_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kw_sessions_project ON public.keyword_search_sessions USING btree (project_id);


--
-- Name: idx_kw_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kw_sessions_status ON public.keyword_search_sessions USING btree (status);


--
-- Name: idx_metrics_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metrics_post ON public.post_metrics_history USING btree (post_shortcode);


--
-- Name: idx_posts_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_deleted_at ON public.posts USING btree (deleted_at);


--
-- Name: idx_posts_is_hidden; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_is_hidden ON public.posts USING btree (is_hidden);


--
-- Name: idx_posts_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_owner ON public.posts USING btree (owner_username);


--
-- Name: idx_posts_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_type ON public.posts USING btree (type);


--
-- Name: idx_posts_view_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_view_count ON public.posts USING btree (view_count DESC);


--
-- Name: idx_project_posts_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_posts_post ON public.project_posts USING btree (post_shortcode);


--
-- Name: idx_project_posts_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_posts_project ON public.project_posts USING btree (project_id);


--
-- Name: idx_project_profiles_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_profiles_project ON public.project_profiles USING btree (project_id);


--
-- Name: idx_project_profiles_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_profiles_username ON public.project_profiles USING btree (username);


--
-- Name: idx_projects_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_user ON public.projects USING btree (user_id);


--
-- Name: idx_relations_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relations_post ON public.post_relations USING btree (post_shortcode);


--
-- Name: idx_relations_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relations_user ON public.post_relations USING btree (username);


--
-- Name: idx_scrape_jobs_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_jobs_post ON public.scrape_jobs USING btree (post_shortcode);


--
-- Name: idx_scrape_jobs_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_jobs_session ON public.scrape_jobs USING btree (session_id);


--
-- Name: idx_scrape_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_jobs_status ON public.scrape_jobs USING btree (status);


--
-- Name: idx_scrape_sessions_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_sessions_project ON public.scrape_sessions USING btree (project_id);


--
-- Name: idx_scrape_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_sessions_status ON public.scrape_sessions USING btree (status);


--
-- Name: idx_scrape_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_sessions_user ON public.scrape_sessions USING btree (user_id);


--
-- Name: idx_search_keywords_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_keywords_keyword ON public.search_keywords USING btree (keyword);


--
-- Name: idx_search_keywords_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_keywords_project ON public.search_keywords USING btree (project_id);


--
-- Name: idx_search_keywords_source_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_keywords_source_type ON public.search_keywords USING btree (project_id, source_type);


--
-- Name: idx_tiktok_comments_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_comments_keyword ON public.tiktok_comments USING btree (keyword_id);


--
-- Name: idx_tiktok_comments_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_comments_username ON public.tiktok_comments USING btree (commenter_username);


--
-- Name: idx_tiktok_comments_video; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_comments_video ON public.tiktok_comments USING btree (video_id);


--
-- Name: idx_tiktok_creators_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_creators_username ON public.tiktok_creators USING btree (username);


--
-- Name: idx_tiktok_hashtags_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_hashtags_keyword ON public.tiktok_hashtags USING btree (keyword_id);


--
-- Name: idx_tiktok_hashtags_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_hashtags_tag ON public.tiktok_hashtags USING btree (tag);


--
-- Name: idx_tiktok_hashtags_video; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_hashtags_video ON public.tiktok_hashtags USING btree (video_id);


--
-- Name: idx_tiktok_videos_capture_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_capture_status ON public.tiktok_videos USING btree (capture_status);


--
-- Name: idx_tiktok_videos_creator; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_creator ON public.tiktok_videos USING btree (creator_id);


--
-- Name: idx_tiktok_videos_included_reach; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_included_reach ON public.tiktok_videos USING btree (included_in_reach);


--
-- Name: idx_tiktok_videos_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_keyword ON public.tiktok_videos USING btree (keyword_id);


--
-- Name: idx_tiktok_videos_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_project ON public.tiktok_videos USING btree (project_id);


--
-- Name: idx_tiktok_videos_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tiktok_videos_session ON public.tiktok_videos USING btree (session_id);


--
-- Name: idx_user_scraped_posts_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_scraped_posts_post ON public.user_scraped_posts USING btree (post_shortcode);


--
-- Name: idx_user_scraped_posts_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_scraped_posts_user ON public.user_scraped_posts USING btree (user_id);


--
-- Name: comment_scrape_logs comment_scrape_logs_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_scrape_logs
    ADD CONSTRAINT comment_scrape_logs_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: comment_scrape_logs comment_scrape_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_scrape_logs
    ADD CONSTRAINT comment_scrape_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: comments comments_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: keyword_search_sessions keyword_search_sessions_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.keyword_search_sessions
    ADD CONSTRAINT keyword_search_sessions_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE CASCADE;


--
-- Name: keyword_search_sessions keyword_search_sessions_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.keyword_search_sessions
    ADD CONSTRAINT keyword_search_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: post_metrics_history post_metrics_history_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_metrics_history
    ADD CONSTRAINT post_metrics_history_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: post_relations post_relations_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_relations
    ADD CONSTRAINT post_relations_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: post_relations post_relations_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_relations
    ADD CONSTRAINT post_relations_username_fkey FOREIGN KEY (username) REFERENCES public.ig_users(username) ON DELETE CASCADE;


--
-- Name: posts posts_owner_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_owner_username_fkey FOREIGN KEY (owner_username) REFERENCES public.ig_users(username) ON DELETE CASCADE;


--
-- Name: project_posts project_posts_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_posts
    ADD CONSTRAINT project_posts_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: project_posts project_posts_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_posts
    ADD CONSTRAINT project_posts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: project_profiles project_profiles_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_profiles
    ADD CONSTRAINT project_profiles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: project_profiles project_profiles_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_profiles
    ADD CONSTRAINT project_profiles_username_fkey FOREIGN KEY (username) REFERENCES public.ig_users(username) ON DELETE CASCADE;


--
-- Name: projects projects_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: scrape_jobs scrape_jobs_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_jobs
    ADD CONSTRAINT scrape_jobs_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: scrape_jobs scrape_jobs_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_jobs
    ADD CONSTRAINT scrape_jobs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.scrape_sessions(id) ON DELETE CASCADE;


--
-- Name: scrape_sessions scrape_sessions_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_sessions
    ADD CONSTRAINT scrape_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;


--
-- Name: scrape_sessions scrape_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_sessions
    ADD CONSTRAINT scrape_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: search_keywords search_keywords_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_keywords
    ADD CONSTRAINT search_keywords_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: tiktok_comments tiktok_comments_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_comments
    ADD CONSTRAINT tiktok_comments_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE SET NULL;


--
-- Name: tiktok_graphql_captures tiktok_graphql_captures_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_graphql_captures
    ADD CONSTRAINT tiktok_graphql_captures_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE SET NULL;


--
-- Name: tiktok_graphql_captures tiktok_graphql_captures_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_graphql_captures
    ADD CONSTRAINT tiktok_graphql_captures_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.keyword_search_sessions(id) ON DELETE SET NULL;


--
-- Name: tiktok_hashtags tiktok_hashtags_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_hashtags
    ADD CONSTRAINT tiktok_hashtags_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE SET NULL;


--
-- Name: tiktok_keyword_creators tiktok_keyword_creators_creator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_keyword_creators
    ADD CONSTRAINT tiktok_keyword_creators_creator_fkey FOREIGN KEY (creator_id) REFERENCES public.tiktok_creators(id) ON DELETE CASCADE;


--
-- Name: tiktok_keyword_creators tiktok_keyword_creators_keyword_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_keyword_creators
    ADD CONSTRAINT tiktok_keyword_creators_keyword_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE CASCADE;


--
-- Name: tiktok_videos tiktok_videos_creator_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.tiktok_creators(id) ON DELETE SET NULL;


--
-- Name: tiktok_videos tiktok_videos_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.search_keywords(id) ON DELETE CASCADE;


--
-- Name: tiktok_videos tiktok_videos_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: tiktok_videos tiktok_videos_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiktok_videos
    ADD CONSTRAINT tiktok_videos_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.keyword_search_sessions(id) ON DELETE SET NULL;


--
-- Name: user_scraped_posts user_scraped_posts_post_shortcode_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_scraped_posts
    ADD CONSTRAINT user_scraped_posts_post_shortcode_fkey FOREIGN KEY (post_shortcode) REFERENCES public.posts(shortcode) ON DELETE CASCADE;


--
-- Name: user_scraped_posts user_scraped_posts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_scraped_posts
    ADD CONSTRAINT user_scraped_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict OhscuvA8vhpifGFtuzUQ9YHVuLfW0xp43ZUSNajfAMgbDnOddDG9xdsZ4FIY5EF

